### ISSUE TITLE
Not able to install in Anaconda platform

### ISSUE THREAD

**Issue by gauravRRI** [luli/hedp#6]
While installing hedp module in anaconda platform, at the last step `python setup.py install` , I always get an  error:

```
 error: can't copy 'hedp/data/db': doesn't exist or not a regular file` .
```

Please help me out here.

**Comment by rth** [comment]
@gauravRRI  Thanks for submitting this issue. I can reproduce it now and I am looking for a solution. As a temporary workaround you can use `python setup.py develop`  instead of `python setup.py install` which should work.

**Comment by rth** [comment]
@gauravRRI  Ok, `python setup.py install` should also work now. Let me know if you still experience problems.

**Comment by gauravRRI** [comment]
it's working now.. I have no issue with installation now . Thanks
